base_path: ./tests
tests:
  - name: Test User Count
    query_file: tests/queries/user_count.sql
    input_file: tests/inputs/users.csv
    expected_output: expected/user_count.csv
    table_name: users
