base_path: ./tests
tests:
  - name: Test User Count
    input_file: inputs/users.csv
    schema_overrides:
      age: INTEGER
    query_file: queries/user_count.sql
    expected_output: expected/user_count.csv
    table_name: users

